languageCode = "zh-cn"
languageName = "中文"
weight = 1
title = "ToneTone"

[params]
displayName = "中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2 January 2006"
description = "我们是ToneTone，一个由程序员和音乐爱好者共同组成的团队。我们深知在编程的世界里，AI的辅助让我们的日常工作效率和创造力得到了极大的提升。"
copyright = "© { year } ToneTone · 粤ICP备2024278723号"
# logo = "img/logo.png"
# secondaryLogo = "img/logo.png"

[author]
name = "ToneTone"
image = "img/logo.png"
headline = "为你提供更加专业，易用的音乐AI工具"
bio = "一个由音乐爱好者和程序员组成的团队，希望带给你专业的音乐体验！"
links = [
  { github = "https://github.com/X-ToneTone" },
  { link = "https://raw.githubusercontent.com/X-ToneTone/shares/main/wechat.jpg" },
]
