# workflow 工作流的名字，自定义
name: ToneTone Index

# 配置触发条件
on:
  push: # 监听到 main 分支的 push 动作
    branches:
      - main

# 工作流的任务集配置
jobs:
  # 定义一个 job，id 为 build
  build:
    name: Build # job 的名字
    runs-on: ubuntu-latest # 指定任务执行的运行器。latest 表示是 GitHub 提供的最新稳定映像，但可能不是操作系统供应商提供的最新版本.
    steps: # 每一个 step 或者是执行一个 action，或者是执行一个命令
      # - name: Checkout # 从仓库中检出代码，供下一步使用
      #   uses: actions/checkout@v4

      # - name: Build
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18.15.0'

      # - name: zip dist
      #   run: |
      #     zip -r tonetone-index.zip ./public ./nginx ./dockerfile

      # - name: scp to Server # 传输文件到服务器
      #   uses: cross-the-world/scp-pipeline@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     user: ${{ secrets.SERVER_USER }}
      #     pass: ${{ secrets.SERVER_PASS }}
      #     connect_timeout: 10s
      #     local: './tonetone-index.zip' # 源路径（工作流）
      #     remote: /usr/local/github/tonetone-index # 目标路径（服务器）

      # - name: remove files
      #   run: rm -rf ./*

      # - name: Deploy to Server # 执行部署任务
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASS }}
      #     script: |
      #       cd /usr/local/github/tonetone-index
      #       unzip -o tonetone-index.zip
      #       docker kill tonetone-index
      #       docker rm tonetone-index
      #       docker rmi tonetone-index
      #       docker build -t tonetone-index.
      #       docker run -d --name tonetone-index --ip localhost -p 8000:80 tonetone-index

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd /usr/local/github/tonetone-index
            rm -rf ./*
            git clone --depth 1 https://gitclone.com/github.com/X-ToneTone/index.git
            cd ./index
            docker kill tonetone-index
            docker rm tonetone-index
            docker rmi tonetone-index
            docker build -t tonetone-index .
            docker run -d --name tonetone-index --ip localhost -p 8000:80 tonetone-index
